Assignment1/Assignment1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Assignment1/assignment1/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from rest_framework.authtoken import views

urlpatterns = [
    path('', include('main.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    # path('api-token-auth', views.obtain_auth_token),
    path('admin/', admin.site.urls),
    path('', include('pwa.urls'))
]

Assignment1/main/urls.py
from django.urls import path
from . import views, templates
from django.views.generic.base import TemplateView

# from .views import UserDetailAPI, RegisterUserAPIView

app_name = "main"


urlpatterns = [
    path('login', views.login_request, name="login"),
    path('registration', views.register_request, name="registration"),
    path('map', TemplateView.as_view(template_name="userMap.html"), name="map"),
    path('home', TemplateView.as_view(template_name="home.html"), name="home"),
    path('logout', views.logout_request, name="logout"),
    path('updatedb/', views.update_database, name='update_db'),
    path('nearbyattract/', views.nearby_attractions, name="nearby_attractions"),
    path('savedmap', TemplateView.as_view(template_name="savedMap.html"), name="savedmap"),
    path('savedview/', views.view_saved, name="view_saved")
]

Assignment1/main/models.py
from django.contrib import admin
from django.contrib.gis.db import models
from django.contrib.auth import get_user_model
# Register your models here.
from django.contrib.auth.models import AbstractUser, BaseUserManager


User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    username = models.CharField(max_length=150, primary_key=True)
    locations = models.CharField(max_length=350, null=True)

    def __str__(self):
        return f"{self.user}"

Assignment1/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from .models import Profile


class NewUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class SaveLocationForm(forms.Form):

    class Meta:
        model = Profile
        fields = ('location',)

    def __init__(self, *args, **kwargs):
        coordinate = kwargs['data'].pop('coordinate', None)
        if coordinate:
            coordinate = coordinate.replace(',', '')  # remove comma, as we need single space between two numbers.
            kwargs['data']['coordinate'] = f'SRID=4326;POINT({coordinate})'

        super(SaveLocationForm, self).__init__(*args, **kwargs)

Assignment1/main/views.py
# views.py
import requests
from django.contrib.gis.geos import Point, Polygon
from django.core.mail.backends import console
from django.http import JsonResponse, request
from django.shortcuts import render, redirect
from .forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile
from django.contrib.auth.decorators import login_required
import json
import overpy


# Create your views here.
def register_request(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = request.POST.get('username')
			user_profile = Profile(user=user, username=username)
			user_profile.save()
			save_trip = Profile(user=user, username=username)
			save_trip.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("login")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = UserCreationForm()
	return render(request=request, template_name="registration/register.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, "You are now logged in as {username}.")
				return redirect("main:map")
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="registration/login.html", context={"login_form":form})

@login_required
def update_database(request):

    saveLoc = request.POST.get("locations", None)

    try:

        # my_coords = [float(coord) for coord in locations.split(", ")]
        my_profile = request.user.profile
        my_profile.locations = saveLoc
        my_profile.save()

        message = f"Updated {request.user.username} with {f'POINT({saveLoc})'}"

        return JsonResponse({"message": message}, status=200)
    except:
        return JsonResponse({"message": saveLoc}, status=400)



@login_required
def logout_request(request):
	logout(request)
	messages.info(request, "Successfully logged out!")
	return redirect("main:home")



@login_required
def nearby_attractions(request):
	try:
		#create overpass object
		api = overpy.Overpass()

		#get coords of map box
		bounding_box = request.POST.get("bbox", None)
		print("BBOX: ", bounding_box)

		# changing the bounding box to have correct coords for the map box
		if bounding_box:
			bbox = bounding_box.split(",")

			shuffled_bbox = [bbox[1], bbox[0], bbox[3], bbox[2]]
			mod_boundingbox = [float(item) for item in shuffled_bbox]
			bounding_box = mod_boundingbox

		#query to get all tourism attractions within bounding box area
		result = api.query(f"""
        [out:json];
        (

            node["tourism"="attraction"]{tuple(bounding_box)};
            way["tourism"="attraction"]{tuple(bounding_box)};
            relation["tourism"="attraction"]{tuple(bounding_box)};

        );
        out body;
        >;
        out skel qt;
        """)

		print("hola!")

		#if query has no results
		if len(result.nodes) == 0:
			return JsonResponse({"message": "No attractions found!"})


		#array for list of features for each result
		geojson_result = {

			"type": "FeatureCollection",
			"features": [],
		}

		nodes_in_way = []

		for way in result.ways:
			print("hello")
			geojson_feature = {

				"type": "Feature",
				"id": "",
				"geometry": "",
				"properties": {}
			}

			poly = []
			for node in way.nodes:
				#record nodes in a 'way' and adds them to associated array

				#make poly out of nodes in way
				nodes_in_way.append(node.id)
				poly.append([float(node.lon), float(node.lat)])

				try:
					poly = Polygon(poly)
				except:
					continue

				geojson_feature["id"] = f"way_{way.id}"
				geojson_feature["geometry"] = json.loads(poly.centroid.geojson)
				geojson_feature["properties"] = {}

				for k, v in way.tags.items():
					geojson_feature["properties"][k] = v
				print(geojson_feature)

				geojson_result["features"].append(
					geojson_feature)  # adding all the information of the mosque to the geojson object
				print(geojson_result)

			for node in result.nodes:
				#skip nodes in way as they have already been processed
				if node.id in nodes_in_way:
					continue

				geojson_feature = {
					"type": "Feature",
					"id": "",
					"geometry": "",
					"properties": {}
				}
				point = Point([float(node.lon), float(node.lat)])
				geojson_feature["id"] = f"node_{node.id}"
				geojson_feature["geometry"] = json.loads(point.geojson)
				geojson_feature["properties"] = {}
				for k, v in node.tags.items():
					geojson_feature["properties"][k] = v
				geojson_result["features"].append(geojson_feature)

		return JsonResponse(geojson_result, status=200)
	# return JsonResponse({"message":"yay"}, status=200)
	except Exception as e:
		return JsonResponse({"message": f"Error: {e}."}, status=400)

@login_required
def view_saved(request):
	userFilter = request.user.username;

	loc_query = Profile.objects.values('locations').filter(username=userFilter).values_list('locations', flat=True)
	location = loc_query[0]

	context = {
		"locationData": location
	}

	return render(request, 'savedMap.html', context)

Assignment1/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% load pwa %}
{% progressive_web_app_meta %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/867bb275f7.js" crossorigin="anonymous"></script>
    <link rel="manifest" href="manifest.json">
</head>
<body>
    <header>

    {% if user.is_authenticated %}

        <div class="m-2 text-center">
            <button onclick="location.href='{%  url 'logout' %}'" type="button"  style="float: right;" class="btn btn-outline-light">
                 {{ user.username }} : Log Out<br>
            <i class="fa-solid fa-door-open"></i></button>

            </button>
            <button onclick="location.href='{%  url 'main:home' %}'" type="button" style="float: right;margin-right: 5px;"  class="btn btn-outline-light">
             Home<br>
            <i class="fa-solid fa-house"></i>
            </button>

            <h1>AWM Assignment 2</h1>
        </div>

    {% else %}

        <h1>AWM Assignment 2</h1>

    {% endif %}

    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>Aaron Groarke (C19373983)</p>
    </footer>
</body>
</html>

Assignment1/main/templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}

<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

    {% if user.is_authenticated %}

        <div class="m-2 text-center">
            Hi {{ user.username }}! Welcome to this site!
        </div>

        <div class="m-2 text-center">
            <button onclick="location.href='{% url 'main:map' %}'" type="button" class="btn btn-outline-success">
             Create Trip<br>
            <i class="fa-regular fa-square-plus"></i>
            </button>

            <button onclick="location.href='{% url 'main:view_saved' %}'" type="button" class="btn btn-outline-success">
             View Saved Trip<br>
            <i class="fa-solid fa-magnifying-glass"></i>
            </button>

        </div>
    {% else %}
        <div class="m-2 text-center">
            <button onclick="location.href='{% url 'login' %}'" type="button" class="btn btn-outline-primary">
             Log In<br><i class="fa-solid fa-right-to-bracket"></i></button>

            <button onclick="location.href='{% url 'main:registration' %}'" type="button" class="btn btn-outline-primary">
             Register<br><i class="fa-solid fa-pen-to-square"></i></button>
        </div>
    {% endif %}
{% endblock %}

Assignment1/main/templates/register/register.html
{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

Assignment1/main/templates/savedMap.html
{% extends 'base.html' %}
{% block content %}
{% load leaflet_tags %}
{% load static %}


<head>

     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
     integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
     crossorigin=""/>
     <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script></head>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
<body>

    <div class="m-2 text-center">
        <h4>Saved Trip:</h4>
    </div>

    <form action="/updatedb" method="post">
        {% csrf_token %}
    </form>

        <div class="m-2 text-center">
            <div id="loadingIcon">
                <div class="spinner-grow text-dark" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <div class="spinner-grow text-secondary" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <div class="spinner-grow text-light" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>

    <div id="map-container">
        <div id="map"></div>
    </div>
</body>

<script type="text/javascript">

    var savedLoc = "{{locationData|safe}}";
    let coordArray = []
    let locationArray = savedLoc.split("|")
    console.log("'" + locationArray[0] + "'" +" + " + "'" + locationArray[1] + "'" + " + " + locationArray.length)

    //display loading icons
    let loadHide = document.getElementById('loadingIcon')
    loadHide.style.display = 'block'
     loadHide.style.visibility = 'visible'

     map = L.map('map', {doubleClickZoom: false}).locate({setView: true, maxZoom: 14});
     L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);

     function onLocationFound(e) {
        var radius = e.accuracy;

         L.circleMarker(e.latlng).addTo(map)
            .bindPopup("You are within " + radius + " meters from this point").openPopup();

        L.circle(e.latlng, radius).addTo(map);

        nearbyAttractions();
    }

    map.on('locationfound', onLocationFound);

     //iterates through until every waypoint has been routed
     for(let i=0;i<locationArray.length - 1;i++) {

         //formats code correctly for use in routing
         coord1Array = locationArray[i].split(",")
         coord2Array = locationArray[i+1].split(",")

         console.log("|" +locationArray[0] +"|")
         //maps the route
        route = L.Routing.control({
            waypoints: [
                L.latLng(coord1Array[0], coord1Array[1]),
                L.latLng(coord2Array[0], coord2Array[1])
            ],
            routeWhileDragging: true
        }).addTo(map);
    }

     function getCookie(cname) {
     var name = cname + "=";
     var ca = document.cookie.split(';');
     for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if(c.indexOf(name) == 0)
           return c.substring(name.length,c.length);
     }
     return "";
    }


     function nearbyAttractions() {

        let csrftoken = getCookie('csrftoken');

        //set map boundary and post to associated view

        let bbox = map.getBounds().toBBoxString()
        console.log("bbox: " + bbox);

        $.ajax({
            type: "POST",
            url: '{% url 'main:nearby_attractions' %}',
            headers: {

                'X-CSRFToken': csrftoken
            },
            data: {

                bbox: map.getBounds().toBBoxString()
            }
        }).done(function (data, status, xhr) {

            console.log(data);

            let markerStyle = {
                radius: 7,
                fillColor: "red",
                color: "black",
                weight: 1,
                opacity: 1,
                fillOpacity: 0.5
            }

            //Map results from view api query
            let geoJsonLayer = L.geoJson(data, {

                pointToLayer: function (feature, latlng) {
                    let marker = L.circleMarker(latlng, markerStyle);
                    name = feature.properties.name;
                    website = feature.properties.website
                    wheelchair = "" + feature.properties["wheelchair:description"]
                    marker.bindPopup("<h7><u><strong>Attraction Info:</strong></u></h7><br>" + "Name: " + name + "<br/>Website: " + website + "<br/>"+ "Wheelchair Accessible: " + wheelchair + "<br/>")

                    return marker
                },
            }).addTo(map);

            map.addLayer(geoJsonLayer);

        }).fail(function (xhr, status, error) {
            var message = "OSM Overpass query failed.<br/>";
            console.log("Status: " + xhr.status + " " + xhr.responseText);
            showOkAlert(message);
        }).always(function () {
            //hide loading
            loadHide.style.display = 'none'
            loadHide.style.visibility = 'hidden'
        });

    }
</script>

{% endblock %}

Assignment1/main/templates/userMap.html
{% extends 'base.html' %}
{% block content %}
{% load leaflet_tags %}
{% load static %}


<head>

     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
     integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
     crossorigin=""/>
     <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" /></head>
<body>

    <form action="/updatedb" method="post">
        {% csrf_token %}
    </form>

    <div class="m-2 text-center">
        <h4>Create Trip:</h4>

        <div id="loadingIcon">
            <div class="spinner-grow text-dark" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>

            <div class="spinner-grow text-secondary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>

            <div class="spinner-grow text-light" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>

        <div id="option-container">
            <button onclick="removeMarker()" class="btn btn-outline-danger">Remove Location <i class="fa-solid fa-trash"></i></button>
            <button onclick="saveTrip()" class="btn btn-outline-success">Save Trip <i class="fa-solid fa-floppy-disk"></i></button>
        </div>

        <div id="map-container">
            <div id="map"></div>
        </div>

    </div>
</body>

<script type="text/javascript">

     map = L.map('map', {doubleClickZoom: false}).locate({setView: true, maxZoom: 14});
     L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);

     //make loading icon visible
    let loadHide = document.getElementById('loadingIcon')
    loadHide.style.display = 'block'
     loadHide.style.visibility = 'visible'

     let startLoc;
     let currLoc= [];
     let route= [];
     let counter = 0;
     let locString = [];

    function onLocationFound(e) {
        var radius = e.accuracy;

        L.marker(e.latlng).addTo(map)
            .bindPopup("You are within " + radius + " meters from this point").openPopup();

        L.circle(e.latlng, radius).addTo(map);

        //add start location to array which will contain each waypoint
        locString[counter] = e.latlng.lat + ", " + e.latlng.lng;

         startLoc = e;
         nearbyAttractions();

         console.log(startLoc);
         console.log(e.latlng)
    }

    map.on('locationfound', onLocationFound);

    function removeMarker(){
        //if there is a location added (not including start)
        if(counter != 0) {
            //removes last location and reverts all variables by 1
            currLoc.splice[counter, 1]
            counter = counter - 1;
            map.removeControl(route[counter])

        }
    }

    function onMapClick(e) {

        console.log("ex" + e.latlng);

        //limit amount of added locations to 5
        if(counter < 5) {

            //if no locations added yet
            if (counter == 0) {

                //map route from start
                route[counter] = L.Routing.control({
                    waypoints: [
                        L.latLng(startLoc.latlng),
                        L.latLng(e.latlng)
                    ],
                    routeWhileDragging: true
                }).addTo(map);

            } else {

                //map route from current
                route[counter] = L.Routing.control({
                    waypoints: [
                        L.latLng(currLoc[counter].latlng),
                        L.latLng(e.latlng)
                    ],
                    routeWhileDragging: true
                }).addTo(map);

            }

            console.log("route" + counter + ":" + route[counter].waypoints)

            //format waypoint for later use
            let locString1 = e.latlng.lat + ", " + e.latlng.lng;

            console.log("a -" + locString)
            counter++;

            //add latest waypoint to locString array
            locString[counter] = locString1
            currLoc[counter] = e

        } else {
            alert("You may only add up to 5 locations!")
        }


    }

    function saveTrip(){
        //iterate through array containing all coords and put them in 1 string
        let saveString = "";
        for(i=0;i<=counter;i++){
            saveString += locString[i] + "|"
        }

        console.log("saved = " + saveString)
        update_db(saveString)
    }

    map.on('click', onMapClick);

    function getCookie(cname) {
     var name = cname + "=";
     var ca = document.cookie.split(';');
     for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if(c.indexOf(name) == 0)
           return c.substring(name.length,c.length);
     }
     return "";
    }

    //update db with all waypoints string
    function update_db(locString) {
    $.ajax({
        type: "POST",
        headers: {
            'X-CSRFToken': getCookie('csrftoken')
        },
        url:"updatedb/",
        data: {
            locations: locString
        {#        {#}
        {#    point0: locString[0],#}
        {#    point1: locString[1],#}
        {#    point2: locString[2],#}
        {#    point3: locString[3],#}
        {#    point4: locString[4],#}
        {#    point5: locString[5]}#}

        }
    }).done(function (data, status, xhr) {
        console.log(data["message"])
        var originalMsg = $(".toast-body").html();
        $(".toast-body").html(originalMsg + "<br/>Updateddatabase<br/>" + data["message"]);
    }).fail(function (xhr, status, error) {
        console.log(error);
        var originalMsg = $(".toast-body").html();
        $(".toast-body").html(originalMsg + "<br/>" + error);
    }).always(function () {
        console.log("find_loc_ed finished");
        $(".toast").toast('show');
    });
    window.location.href='{% url 'main:home' %}'
}

     function nearbyAttractions() {

                let csrftoken = getCookie('csrftoken');

                //set map boundary and post to associated view

                let bbox = map.getBounds().toBBoxString()
                console.log("bbox: " + bbox);

                $.ajax({
                    type: "POST",
                    url: '{% url 'main:nearby_attractions' %}',
                    headers: {

                        'X-CSRFToken': csrftoken
                    },
                    data: {

                        bbox: map.getBounds().toBBoxString()
                    }
                }).done(function (data, status, xhr) {

                    console.log(data);

                    let markerStyle = {
                        radius: 7,
                        fillColor: "red",
                        color: "black",
                        weight: 1,
                        opacity: 1,
                        fillOpacity: 0.5
                    }

                    //Map results from view api query
                    let geoJsonLayer = L.geoJson(data, {

                        pointToLayer: function (feature, latlng) {
                            let marker = L.circleMarker(latlng, markerStyle);
                            name = feature.properties.name;
                            website = feature.properties.website
                            wheelchair = "" + feature.properties["wheelchair:description"]
                            marker.bindPopup("<h7><u><strong>Attraction Info:</strong></u></h7><br>" + "Name: " + name + "<br/>Website: " + website + "<br/>"+ "Wheelchair Accessible: " + wheelchair + "<br/>")

                            return marker
                        },
                    }).addTo(map);

                    map.addLayer(geoJsonLayer);

                }).fail(function (xhr, status, error) {
                    var message = "OSM Overpass query failed.<br/>";
                    console.log("Status: " + xhr.status + " " + xhr.responseText);
                    showOkAlert(message);
                }).always(function () {
                    //hide loading icons
                    loadHide.style.display = 'none'
                    loadHide.style.visibility = 'hidden'
                });

            }



</script>

{% endblock %}